### PR TITLE
Update AgameR Hats Mod PE.js

### PR DESCRIPTION
**Pull request by RandomAltThing**
Updated some stuff

### CODE REVIEW

**Comment by peacestorm** [comment]
Thanks for these little improvements! Expect a 1.2.2 release soon with this included!

**Comment by RandomAltThing** [comment]
Can't wait! I'm gonna try and add more hats soon.

**Comment by peacestorm** [comment]
2.0 will have new hats and a GUI. 1.2.2 is the last 1.X release.

**Comment by RandomAltThing** [comment]
You could just make it so you wear what's in your hand. But GUI sounds cool too.

**Pull request merged**
